// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://heenamqtjxvhoonhkisv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhlZW5hbXF0anh2aG9vbmhraXN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg2NDQ3MDQsImV4cCI6MjA4NDIyMDcwNH0.fGUEIIZhw1If8UONOYvjiKe7pJHnSY8jyo5lSFNDlbA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});